language: elixir

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3
    - otp_release: 19.3
      elixir: 1.3
    - otp_release: 18.3
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.4
    - otp_release: 20.2
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.5
    - otp_release: 20.2
      elixir: 1.5
    - otp_release: 20.2
      elixir: 1.6

env:
  global:
  - MIX_ENV=test

sudo: false

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

before_script:
  - env TRAVIS=false mix compile
  - mix ejabberd.gen.config

script:
  - mix test

after_script:
  - mix coveralls.travis
